apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    path: test-app
    repoURL: https://github.com/umizoom/SM-workshop-1
    directory:
      include: "*.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
    automated: {}
